server:
  port: ${PORT}
spring:
  application:
    name: price
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 1000
          multiplier: 1.5
          max-interval: 10000